name: Release

on:
  push:
    tags:
      - '*'

env:
    NIMVER:  "2.2.4"
    ZIGVER:  "0.14.1"

jobs:
  build:
    # On paper, we can cross-compile with zig from all platforms to all platforms.
    # But the Mac build requires the Mac SDK, so we just build everything on Mac.
    runs-on: macos-latest

    steps:
      - name: System Info
        run: |
          echo "System: $(uname -a)"

      - uses: actions/checkout@v4

      - name: Setup Nimble cache
        id: nimble-cache
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ env.NIMVER }}

      - uses: mlugg/setup-zig@7dccf5e6d09267c55f815f2db29495f30ba2ebca # v2.0.1
        with:
          version: ${{ env.ZIGVER }}

      - uses: jiro4989/setup-nim-action@3a60cf06f20c1cf3a9becf76b30288c0361d5f1e  # v2.2.2
        with:
          nim-version: ${{ env.NIMVER }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all targets
        run: |
          bash ./scripts/build-all.sh -d:release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true

      - name: List artifacts
        run: ls -laR

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: |
            *
          draft: true
          name: ${{ github.ref_name }}
